### PR TITLE
Feat/protostar generictests deploy (#7)

### PR DESCRIPTION
**Pull request by jobez**
Draft PR for issue #7

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
great start! Going to merge since we are so early

**Comment by milancermak** [comment]
I'm not a fan of the .sh scripts for security reasons. We should refrain from using them.

**Comment by jobez** [comment]
> I'm not a fan of the .sh scripts for security reasons. We should refrain from using them.

If you have the time, do you mind pointing out any glaring issues? I opted to go with bash so I can lean on protostar's functionality, but perhaps I overextended my bash knowledge and incidentally left security issues. I will try to run it through shellcheck.

**Comment by milancermak** [comment]
There's tons of references online. One example - you're using `eval`, which is [evil](http://mywiki.wooledge.org/BashFAQ/048).

I consider shell scripts a necessary evil. They're opaque, hard to write in a secure manner, difficult to review, introduce yet another dependency, are not multi platform, etc.

If the goal here is to write a deploy script, maybe we can utilize protostar's [multicall](https://docs.swmansion.com/protostar/docs/cli-reference#multicall) scripting.

**Pull request merged**
